name: Latest blog post workflow

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with latest articles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://coffey.codes/rss'
          max_post_count: 5
          template: "- [$title]($url) <sub>$date</sub>\n"
          date_format: 'mmm dd, yyyy'
